// This file is auto-generated by build-config.js during deployment
// It allows the frontend to use different API URLs for different environments
window.APP_CONFIG = {
  apiBase: 'https://cusb-website.onrender.com/api',
  uploadBase: 'https://cusb-website.onrender.com'
};
