// This file is auto-generated by build-config.js during deployment
// It allows the frontend to use different API URLs for different environments
window.APP_CONFIG = {
  apiBase: 'http://localhost:5000/api',
  uploadBase: 'http://localhost:5000'
};
